cors:
  allowedHeaders:
    - Authorization
    - Cache-Control
    - Content-Length
    - Content-Range
    - DNT
    - If-Modified-Since
    - User-Agent
    - X-Requested-With
  allowedMethods:
    - CONNECT
    - DELETE
    - GET
    - HEAD
    - OPTIONS
    - OTHER
    - PATCH
    - POST
    - PUT
    - TRACE
  allowedOriginPattern: "*"
mongoConfig:
  connection_string: mongodb+srv://phizzardSuperUser:0e6e2659027c05fb79665be23ca21793a583a65b5d44befbc0d00a4382c05669@orders0-mowjm.mongodb.net/orders?ssl=true&sslInvalidHostNameAllowed=true&streamType=netty
sqsConfig:
  accessKeyId: AKIAJ3KDNXMVJAWHXBRA
  queueName: incoming-orders
  serviceEndpoint: https://sqs.eu-central-1.amazonaws.com/806353235757/incoming-orders
  secretAccessKey: 3dYqPjZJfWyhJwDylaf1gsGvr6kfx6n08E1tl1yQ
  signingRegion: eu-central-1
