cors:
  allowedHeaders:
    - Authorization
    - Cache-Control
    - Content-Length
    - Content-Range
    - DNT
    - If-Modified-Since
    - User-Agent
    - X-Requested-With
  allowedMethods:
    - CONNECT
    - DELETE
    - GET
    - HEAD
    - OPTIONS
    - OTHER
    - PATCH
    - POST
    - PUT
    - TRACE
  allowedOriginPattern: "*"
mongoConfig:
  connection_string: mongodb://127.0.0.1/test_orders?streamType=netty
sqs:
  accessKeyId: x
  queueName: test-orders
  serviceEndpoint: http://localhost:9324
  secretAccessKey: x
  signingRegion: elasticmq
jwtConfig:
  algorithm: ES256
  publicKey: frank
  privateKey: francis