version: '3.7'

services:
  elasticmq:
    build: elasticmq
    container_name: order_queue
    #    networks:
    #      - docker_order_enqueuing_service
    ports:
      - "9324:9324"
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
#    expose:
#      - 27017
    restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
#  mongo2:
#    hostname: mongo2
#    container_name: localmongo2
#    image: mongo:3.6-jessie
#    ports:
#      - "27018:27017"
##    expose:
##      - 27017
#    restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
#  mongo3:
#    hostname: mongo3
#    container_name: localmongo3
#    image: mongo:3.6-jessie
#    ports:
#      - "27019:27017"
##    expose:
##      - 27017
#    restart: always
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
#  mongosetup:
#    image: mongo:3.6-jessie
##    links:
##      - mongo1:mongo1
##      - mongo2:mongo2
##      - mongo3:mongo3
#    depends_on:
#      - mongo1
#      - mongo2
#      - mongo3
#    volumes:
#      - ../localmongo:/scripts
#    restart: "no"
#    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]
  order-enqueuing-service:
    build: app
    container_name: order-enqueuing-service
    image: order-enqueuing-service
#    networks:
#    - docker_order_enqueuing_service
#    - localmongo
    ports:
      - "11080:8080"
    volumes:
      - ./app/build/openapi.yml:/opt/api.yml
      - ./app/build/config.yml:/opt/config.yml
    environment:
    - OPENAPI_PATH=/opt/api.yml
    depends_on:
      - elasticmq
      - mongo1
#      - mongo2
#      - mongo3
#    external_links:
#      - localmongo1:mongo1
#      - localmongo2:mongo2
#      - localmongo3:mongo3

#networks:
#  localmongo:
#    external: true
#    name: localmongo_default
#  docker_order_enqueuing_service:
#    external: true
