version: '3.7'

services:
  elasticmq:
    build: elasticmq
    container_name: elasticmq
    networks:
      - oes
    ports:
      - "9324:9324"
  mongo1:
    container_name: mongo1
    image: mongo:latest
    networks:
      - oes
    ports:
      - "27017:27017"
    restart: always
  order-enqueuing-service:
    command: ["./wait-for-it.sh", "elasticmq:9324", "--", "java", "-jar", "order-enqueuing-service.jar", "/opt/config.yml"]
    container_name: order-enqueuing-service
    depends_on:
      - elasticmq
      - mongo1
    environment:
      - OPENAPI_PATH=/opt/api.yml
    image: order-enqueuing-service
    networks:
      - oes
    ports:
      - "9080:9080"
    volumes:
      - ./app/build/openapi.yml:/opt/api.yml
      - ./app/build/config-docker.yml:/opt/config.yml

networks:
  oes: